[packages.common]
brew = [
  "age",
  "autoenv",
  "bat",
  "bitwarden-cli",
  "btop",
  "chezmoi",
  "commitizen",
  "eza",
  "fd",
  "fzf",
  "gcc",
  "git",
  "imagemagick",
  "lazygit",
  "mise",
  "neovim",
  "oh-my-posh",
  "ripgrep",
  "tmux",
  "tree-sitter-cli",
  "yazi",
  "yq",
  "zoxide",
  "zsh",
]

[packages.ai]
brew = ["fabric-ai", "opencode"]

[packages.k8s]
brew = [
  "argocd",
  "cilium-cli",
  "helm",
  "k9s",
  "kubectx",
  "kubelogin",
  "kubernetes-cli",
  "kyverno",
]

[packages.containers]
brew = ["podman", "podman-tui", "lima"]

[packages.iac]
brew = ["ansible", "terraform", "vault-cli"]

[package.cloud]
brew = ["oci-cli"]

[packages.darwin]
brew = ["borders"]
tap = [""]
casks = [
  "aerospace",
  "betterdisplay",
  "brave-browser",
  "calibre",
  "discord",
  "firefox",
  "firefox@developer-edition",
  "font-jetbrains-mono-nerd-font",
  "ghostty",
  "kap",
  "keka",
  "microsoft-outlook",
  "microsoft-teams",
  "obsidian",
  "proton-mail",
  "protonvpn",
  "qbittorrent",
  "raycast",
  "signal",
  "slack",
  "steam",
  "synology-drive",
  "unnaturalscrollwheels",
  "vlc",
]

[packages.linux]
brew = ["keychain", "xclip"]
